# Generated by Django 5.1.4 on 2024-12-27 15:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userresetpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresetpassword',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 27, 15, 17, 45, 465399, tzinfo=datetime.timezone.utc)),
        ),
    ]
